name: build and test

on: [push]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: docker://mmorse1217/latex-ci:latest
    - name: Build latex document
      run: docker run --rm -v${GITHUB_WORKSPACE}:/latex mmorse1217/latex-ci:latest sh entrypoint.sh
