name: push docker image
on: 
  push:
    paths: 
      - 'Dockerfile'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Latex Base to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mmorse1217/latex-base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        dockerfile: Dockerfile
        buildoptions: "--target latex-base"
    - name: Publish Latex Dev to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mmorse1217/latex-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        dockerfile: Dockerfile
        buildoptions: "--target latex-dev --cache-from=mmorse1217/latex-dev:latest"
